In [9]:
import os
import pandas as pd
import nltk
import requests
import string
from gensim.models import Word2Vec
import shutil
import numpy as np
import re
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
from sklearn.metrics import accuracy_score, classification_report
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.regularizers import l2
import shap


In [29]:
FINE_TUNED_DIR = '../../pretained_or_finetune-models'
REVIEWS_DATASET_DIR = '../../dataset'
UTILS_DIR = '../../utils'
NLTK_DATA_PATH = f"{FINE_TUNED_DIR}/nltk_data"
DIR_MODEL_STORED = f"../../models/BiLSTM_models_sample.keras"

nltk.data.path.append(NLTK_DATA_PATH)

In [3]:
tourism_reviews_en = pd.read_csv(f"{REVIEWS_DATASET_DIR}/eng_reviews_emotion_classify.csv", encoding='utf-8')

columns_to_use = ['helpful_votes', 'location_id', 'review_id', 'review',
                  'review_subject', 'trip_type', 'rating',
                  'location_name', 'province', 'place_id', 'emotion', 'cleaned_review']
columns_to_train = ['location_id', 'review', 'rating']
review_df = tourism_reviews_en[columns_to_use]

In [4]:
tourism_reviews_en.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5909 entries, 0 to 5908
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Unnamed: 0.1    5909 non-null   int64 
 1   Unnamed: 0      5909 non-null   int64 
 2   helpful_votes   5909 non-null   int64 
 3   location_id     5909 non-null   int64 
 4   lang            5909 non-null   object
 5   review_id       5909 non-null   int64 
 6   review          5909 non-null   object
 7   review_subject  5909 non-null   object
 8   trip_type       5892 non-null   object
 9   travel_date     5892 non-null   object
 10  rating          5909 non-null   int64 
 11  location_name   5909 non-null   object
 12  province        5909 non-null   object
 13  place_id        5909 non-null   object
 14  cleaned_review  5909 non-null   object
 15  emotion         5909 non-null   object
dtypes: int64(6), object(10)
memory usage: 738.8+ KB


In [5]:
review_df.describe()

helpful_votes   location_id     review_id       rating
count    5909.000000  5.909000e+03  5.909000e+03  5909.000000
mean        1.058216  6.483167e+06  7.590446e+08     4.153833
std         5.625108  4.877561e+06  1.844114e+08     1.067077
min         0.000000  3.110380e+05  1.049076e+08     1.000000
25%         0.000000  2.578107e+06  6.573250e+08     4.000000
50%         0.000000  6.017599e+06  7.832754e+08     4.000000
75%         1.000000  8.818088e+06  9.240324e+08     5.000000
max       182.000000  2.714283e+07  9.653184e+08     5.000000

In [6]:
review_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5909 entries, 0 to 5908
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   helpful_votes   5909 non-null   int64 
 1   location_id     5909 non-null   int64 
 2   review_id       5909 non-null   int64 
 3   review          5909 non-null   object
 4   review_subject  5909 non-null   object
 5   trip_type       5892 non-null   object
 6   rating          5909 non-null   int64 
 7   location_name   5909 non-null   object
 8   province        5909 non-null   object
 9   place_id        5909 non-null   object
 10  emotion         5909 non-null   object
 11  cleaned_review  5909 non-null   object
dtypes: int64(4), object(8)
memory usage: 554.1+ KB


In [7]:
review_df

helpful_votes  location_id  review_id  \
0                 0      2209612  953596359   
1                 0      2209612  938998692   
2                 6      2209612  933065689   
3                 0      2209612  885904967   
4                 4      2209612  782967555   
...             ...          ...        ...   
5904              0      1831068  888281929   
5905              4      1831068  752115552   
5906              0      1831068  693354319   
5907              1      1831068  573376614   
5908              0      1831068  571939282   

                                                 review  \
0     Besides elegant grand palace and wat pra kaew ...   
1     This is one of the last big king temples of Ba...   
2     It is beautiful, clean and free to enter. Both...   
3     Wat Ratchabophit is a Buddhist temple located ...   
4     Wat Ratchabophit is a historic royal temple bu...   
...                                                 ...   
5904  Is quite far from Korat Town or main highway. ...   
5905  Prasat Pueai Noi is claimed to be the biggest ...   
5906  I think this place is claimed to be the oldest...   
5907  The compound comprises three brick buildings o...   
5908  Fully recommend this to the genuine history bu...   

                                         review_subject        trip_type  \
0     The place is nearby grand palace, in the area ...           Family   
1                                              Nice Wat      Solo travel   
2                                            Nice views      Solo travel   
3     Wat Ratchabophit - a temple characterized by u...          Couples   
4                                   Beautiful, peaceful             NONE   
...                                                 ...              ...   
5904                 Can visit.. depends on individual            Family   
5905                    Small, Isolated Khmer Sanctuary             NONE   
5906                         A sense of ancient times..  Friends getaway   
5907                                 Another Angkor Wat      Solo travel   
5908                          Small, simple, yet qualit          Couples   

      rating     location_name    province   place_id emotion  \
0          5  Wat Ratchabophit     Bangkok  P03013220     joy   
1          4  Wat Ratchabophit     Bangkok  P03013220     joy   
2          4  Wat Ratchabophit     Bangkok  P03013220     joy   
3          5  Wat Ratchabophit     Bangkok  P03013220     joy   
4          5  Wat Ratchabophit     Bangkok  P03013220     joy   
...      ...               ...         ...        ...     ...   
5904       3   Prasat Puay Noi  Nonthaburi  P03013503     joy   
5905       3   Prasat Puay Noi  Nonthaburi  P03013503     joy   
5906       4   Prasat Puay Noi  Nonthaburi  P03013503     joy   
5907       4   Prasat Puay Noi  Nonthaburi  P03013503     joy   
5908       4   Prasat Puay Noi  Nonthaburi  P03013503     joy   

                                         cleaned_review  
0     besides elegant grand palace <OOV> wat pra kae...  
1     <OOV> <OOV> one <OOV> <OOV> last big king temp...  
2     <OOV> <OOV> beautiful clean <OOV> free <OOV> e...  
3     wat ratchabophit <OOV> <OOV> buddhist temple l...  
4     wat ratchabophit <OOV> <OOV> historic royal te...  
...                                                 ...  
5904  <OOV> quite far <OOV> korat town <OOV> main hi...  
5905  prasat pueai noi <OOV> claimed <OOV> <OOV> <OO...  
5906  <OOV> think <OOV> place <OOV> claimed <OOV> <O...  
5907  <OOV> compound comprises three brick buildings...  
5908  fully recommend <OOV> <OOV> <OOV> genuine hist...  

[5909 rows x 12 columns]

In [11]:
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import WordNetLemmatizer

custom_stopwords = set(stopwords.words('english'))
stop_words = custom_stopwords
lemmatizer = WordNetLemmatizer()

In [12]:
def advanced_clean_text(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)  # Remove numbers
    text = re.sub(r'[^a-z\s]', '', text)  # Remove special characters
    text = re.sub(r'\b(u|ur|b4)\b', 'you', text)  # Replace common abbreviations
    words = word_tokenize(text)
    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]
    words = [word for word in words if word not in string.punctuation]
    return ' '.join(words)

In [13]:
# Apply preprocessing to the review texts
review_df['cleaned_review'] = review_df['review'].apply(advanced_clean_text)

# 2. สร้าง Word Embeddings ด้วย Word2Vec
sentences = [row.split() for row in review_df['cleaned_review']]
word2vec_model = Word2Vec(sentences, vector_size=300, window=5, min_count=1, workers=4)  # เปลี่ยน vector_size เป็น 300



/var/folders/fk/449tdf_12hzd2r7ps4659q0m0000gn/T/ipykernel_7777/994389100.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  review_df['cleaned_review'] = review_df['review'].apply(advanced_clean_text)


In [14]:
# Parameters
embedding_dim = 300  # Assuming Word2Vec has 300 dimensions
dropout_rate = 0.5
num_classes = 1  # Binary classification
max_len = 100  # Maximum length of input sequences
ngram_range = (1, 2)  # Unigrams and bigrams
max_features = 20000  

# Create the embedding matrix from the Word2Vec model
word_index = {word: i for i, word in enumerate(word2vec_model.wv.index_to_key)}
embedding_matrix = np.zeros((len(word_index) + 1, embedding_dim))

In [15]:
def text_to_word2vec(tokens, model, max_length=300):
    vector = np.zeros((max_length, 300))
    for i, word in enumerate(tokens):
        if i < max_length:
            if word in model.wv:
                vector[i] = model.wv[word]
    return vector

review_df['embedding'] = review_df['cleaned_review'].apply(lambda x: text_to_word2vec(x, word2vec_model))


/var/folders/fk/449tdf_12hzd2r7ps4659q0m0000gn/T/ipykernel_7777/1367629667.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  review_df['embedding'] = review_df['cleaned_review'].apply(lambda x: text_to_word2vec(x, word2vec_model))


In [16]:
def map_rating_to_sentiment(rating):
    if rating in [1, 2]:
        return 'negative'
    elif rating in [3, 4]:
        return 'neutral'
    else:  # 4 or 5
        return 'positive'

review_df['sentiment'] = review_df['rating'].apply(map_rating_to_sentiment)

/var/folders/fk/449tdf_12hzd2r7ps4659q0m0000gn/T/ipykernel_7777/2638035927.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  review_df['sentiment'] = review_df['rating'].apply(map_rating_to_sentiment)


In [17]:
from sklearn.utils import resample

# Assuming `review_df` is your original DataFrame with a 'sentiment' column

# 1. Separate the data by class
df_positive = review_df[review_df.sentiment == 'positive']
df_neutral = review_df[review_df.sentiment == 'neutral']
df_negative = review_df[review_df.sentiment == 'negative']

# 2. Resample the minority classes
# For example, oversample the neutral and negative classes to match the positive class
df_neutral_upsampled = resample(df_neutral,
                                replace=True,  # Sample with replacement
                                n_samples=len(df_positive),  # Match number of positive class samples
                                random_state=42)  # Reproducible results

df_negative_upsampled = resample(df_negative,
                                 replace=True,  # Sample with replacement
                                 n_samples=len(df_positive),  # Match number of positive class samples
                                 random_state=42)  # Reproducible results

# 3. Combine the resampled DataFrames
df_balanced = pd.concat([df_positive, df_neutral_upsampled, df_negative_upsampled])

# 4. Shuffle the combined DataFrame
df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

# 5. Check the distribution of the classes
print(df_balanced['sentiment'].value_counts())


sentiment
neutral     2871
positive    2871
negative    2871
Name: count, dtype: int64


In [35]:
tokenizer = Tokenizer(num_words=max_features)
tokenizer.fit_on_texts(df_balanced['cleaned_review'])

X = tokenizer.texts_to_sequences(df_balanced['cleaned_review'])
X = pad_sequences(X, maxlen=max_len)

# แปลงคอลัมน์ 'sentiment' เป็นข้อมูลตัวเลข
label_mapping = {'negative': 0, 'neutral': 1, 'positive': 2}
y = df_balanced['sentiment'].map(label_mapping)

In [52]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X, y)

# แบ่งข้อมูลใหม่อีกครั้งหลังจาก SMOTE
X_train_resampled, X_val, y_train_resampled, y_val = train_test_split(X_train_resampled, y_train_resampled, test_size=0.2, random_state=42)

In [53]:
# Check the shapes of the resulting arrays
print(f"X_train shape: {X_train_resampled.shape}")
print(f"y_train shape: {y_train_resampled.shape}")
print(f"X_test shape: {X_val.shape}")
print(f"y_test shape: {y_val.shape}")


X_train shape: (6890, 100)
y_train shape: (6890,)
X_test shape: (1723, 100)
y_test shape: (1723,)


In [56]:
y_val

4205    2
1665    1
3121    2
3126    2
3688    0
       ..
8510    1
7445    2
2132    0
247     1
4011    2
Name: sentiment, Length: 1723, dtype: int64

In [55]:
X_val

array([[   0,    0,    0, ..., 1245,  124, 1254],
       [   0,    0,    0, ..., 1568, 1321, 2532],
       [   0,    0,    0, ...,  272,  345, 1360],
       ...,
       [   0,    0,    0, ...,  426,   19,  651],
       [   0,    0,    0, ...,  193,  497, 1004],
       [   0,    0,    0, ..., 4532,  165, 1071]], dtype=int32)

In [60]:
from keras.models import Sequential
from keras.layers import Embedding, Conv1D, GlobalMaxPooling1D, LSTM, Dense, Dropout

# Step 6: Build the LSTM Model
dropout_rate = 0.5
input_shape = X_train_resampled.shape[1:] 

X_train_reshaped = np.expand_dims(X_train_resampled, axis=1)  # เพิ่มมิติที่ตำแหน่งที่ 1 ให้เป็น (batch_size, 1, embedding_dim)
X_val_reshaped = np.expand_dims(X_val, axis=1)  # เพิ่มมิติที่ตำแหน่งที่ 1

# CNN-LSTM model
model_cnn_lstm = Sequential()
model_cnn_lstm.add(Conv1D(128, kernel_size=1, activation='relu', input_shape=(1, 128)))
model_cnn_lstm.add(GlobalMaxPooling1D())
model_cnn_lstm.add(LSTM(64))
model_cnn_lstm.add(Dropout(0.5))
model_cnn_lstm.add(Dense(1, activation='sigmoid'))
model_cnn_lstm.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])



model_cnn_lstm.summary()

(6890, 100)


ValueError: Input 0 of layer "lstm_6" is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (None, 128)

In [43]:
word_index = tokenizer.word_index
embedding_matrix = np.zeros((len(word_index) + 1, embedding_dim))

for word, i in word_index.items():
    if i < max_features:
        # ใช้ [] แทนการใช้ get() เพื่อดึง embedding vector
        if word in word2vec_model.wv:
            embedding_vector = word2vec_model.wv[word]
            if embedding_vector is not None:
                embedding_matrix[i] = embedding_vector

In [44]:
from sklearn.utils.class_weight import compute_class_weight

unique_classes = np.unique(y_train_resampled)

# Compute class weights
class_weights = compute_class_weight('balanced', classes=unique_classes, y=y_train_resampled)
class_weights_dict = dict(enumerate(class_weights))

# Optional: Normalize class weights
total = sum(class_weights_dict.values())
class_weights_dict = {k: v / total for k, v in class_weights_dict.items()}

In [45]:
class_weights_dict = dict(enumerate(class_weights))

In [46]:
class_weights_dict

{0: 1.0064271107215892, 1: 0.9869646182495344, 2: 1.0068683326026597}

In [48]:
from keras.callbacks import EarlyStopping, ModelCheckpoint

# กำหนดการตั้งค่า Early Stopping และ Model Checkpoint
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
model_checkpoint = ModelCheckpoint(DIR_MODEL_STORED, monitor='val_loss', save_best_only=True)  # เปลี่ยนจาก .h5 เป็น .keras

# ฝึกโมเดล
X_train_reshaped = X_train_resampled.reshape((X_train_resampled.shape[0], 1, X_train_resampled.shape[1]))
X_val_reshaped = X_val.reshape((X_val.shape[0], 1, X_val.shape[1]))

# ฝึกโมเดลด้วยข้อมูลที่ reshaped แล้ว
history = model_cnn_lstm.fit(X_train_reshaped, 
                             y_train_resampled, 
                             epochs=20, 
                             batch_size=64, 
                             callbacks=[early_stopping, model_checkpoint],
                             validation_data=(X_val_reshaped, y_val),
                             class_weight=None)


Epoch 1/20


AttributeError: 'NoneType' object has no attribute 'items'

In [40]:
import matplotlib.pyplot as plt

acc = history.history['accuracy']      # Training accuracy
val_acc = history.history['val_accuracy']  # Validation accuracy
loss = history.history['loss']         # Training loss
val_loss = history.history['val_loss']  # Validation loss

# Plot Accuracy
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)  # Create subplot for accuracy
plt.plot(acc, label='Training Accuracy')
plt.plot(val_acc, label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Plot Loss
plt.subplot(1, 2, 2)  # Create subplot for loss
plt.plot(loss, label='Training Loss')
plt.plot(val_loss, label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

# Display the plots
plt.tight_layout()
plt.show()

AttributeError: 'Sequential' object has no attribute 'history'

In [41]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from keras.models import load_model

# โหลดโมเดล LSTM ที่ดีที่สุด
best_model = load_model(DIR_MODEL_STORED)

In [42]:
# ใช้โมเดล LSTM ทำนายข้อมูล validation set
lstm_preds = best_model.predict(X_val)
lstm_preds = np.argmax(lstm_preds, axis=1)

# ฝึก Gradient Boosting Classifier บนผลลัพธ์จาก LSTM
gb_clf = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb_clf.fit(lstm_preds.reshape(-1, 1), y_val)

# ทำนายผลลัพธ์ด้วย Gradient Boosting
ensemble_preds = gb_clf.predict(lstm_preds.reshape(-1, 1))

# ตรวจสอบผลลัพธ์
print(classification_report(y_val, ensemble_preds))
print(confusion_matrix(y_val, ensemble_preds))

54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       589
           1       0.00      0.00      0.00       544
           2       0.34      1.00      0.51       590

    accuracy                           0.34      1723
   macro avg       0.11      0.33      0.17      1723
weighted avg       0.12      0.34      0.17      1723

[[  0   0 589]
 [  0   0 544]
 [  0   0 590]]


/Users/ittichaiboonyarakthunya/Library/Caches/pypoetry/virtualenvs/is-project-thailand-tourism-recommendation-qwL-LsgH-py3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/ittichaiboonyarakthunya/Library/Caches/pypoetry/virtualenvs/is-project-thailand-tourism-recommendation-qwL-LsgH-py3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/ittichaiboonyarakthunya/Library/Caches/pypoetry/virtualenvs/is-project-thailand-tourism-recommendation-qwL-LsgH-py3.12/lib/python

In [143]:
lstm_preds = best_model.predict(X_val)
lstm_preds = np.argmax(lstm_preds, axis=1)

print(classification_report(y_val, lstm_preds))
print(confusion_matrix(y_val, lstm_preds))

54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step
              precision    recall  f1-score   support

           0       0.95      0.98      0.97       589
           1       0.51      0.68      0.58       544
           2       0.60      0.41      0.48       590

    accuracy                           0.69      1723
   macro avg       0.69      0.69      0.68      1723
weighted avg       0.69      0.69      0.68      1723

[[579   8   2]
 [ 17 368 159]
 [ 11 340 239]]


In [94]:
# สร้างโมเดล Random Forest (Bagging)
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_resampled, y_train_resampled)
rf_predictions = rf_model.predict(X_val)

# สร้างโมเดล Gradient Boosting (Boosting)
gb_model = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb_model.fit(X_train_resampled, y_train_resampled)
gb_predictions = gb_model.predict(X_val)

# วัดผลลัพธ์ของแต่ละโมเดล
print("Random Forest Accuracy:", accuracy_score(y_val, rf_predictions))
print("Gradient Boosting Accuracy:", accuracy_score(y_val, gb_predictions))

Random Forest Accuracy: 0.8276262333139872
Gradient Boosting Accuracy: 0.6604759141033082


In [97]:
# Ensemble วิธี Voting (Hard Voting)
from sklearn.ensemble import VotingClassifier

# รวมโมเดลทั้งสองด้วยการ Voting
voting_model = VotingClassifier(estimators=[
    ('rf', rf_model), ('gb', gb_model)],
    voting='hard')

voting_model.fit(X_train_resampled, y_train_resampled)
voting_predictions = voting_model.predict(X_val)

# วัดผลลัพธ์จากการใช้ Voting
print("Voting Ensemble Accuracy:", accuracy_score(y_val, voting_predictions))

Voting Ensemble Accuracy: 0.6993615786419036


In [98]:
y_val

4205    2
1665    1
3121    2
3126    2
3688    0
       ..
8510    1
7445    2
2132    0
247     1
4011    2
Name: sentiment, Length: 1723, dtype: int64

In [112]:
common_indices = y_val.index.intersection(review_df.index)
missing_indices = y_val.index.difference(review_df.index)
print(f"Common indices count: {len(common_indices)}")
print(f"Missing indices count: {len(missing_indices)}")

Common indices count: 1170
Missing indices count: 553


In [110]:
# y_val = y_val.iloc[:-1]

In [107]:
predict_label = y_val

In [113]:
redicted_df = pd.DataFrame({'predicted': ensemble_preds}, index=y_val.index)
    
    # Concatenate y_val and the new predicted_df to create a new DataFrame
predict_df = pd.concat([y_val, redicted_df], axis=1)

In [115]:
predict_df

sentiment  predicted
4205         2          1
1665         1          1
3121         2          2
3126         2          1
3688         0          0
...        ...        ...
8510         1          1
7445         2          2
2132         0          0
247          1          1
4011         2          2

[1723 rows x 2 columns]

In [116]:
valid_y_val = predict_df.loc[predict_df.index.isin(review_df.index)]

# Now you can safely use .loc with valid_y_val indices
filtered_reviews = review_df.loc[valid_y_val.index]

In [117]:
filtered_reviews

helpful_votes  location_id  review_id  \
4205              0     11867768  660193827   
1665              0     16868178  893223254   
3121              1       556614  874997345   
3126              0      6669517  632751727   
3688              1      7659431  613000573   
...             ...          ...        ...   
469               0      8874054  875897422   
4129              1      1307603  750690836   
2132              0       554864  696305303   
247               0     25571501  929540899   
4011              1      2359241  931977927   

                                                 review  \
4205  The place is a real gem, nestling in the cool ...   
1665  Nice view, but you need to be be careful when ...   
3121  Doi Mae Salong is a beautiful and interesting ...   
3126  Located on the way we back to our accommodatio...   
3688  i stayed on koh larn at the castello resort ov...   
...                                                 ...   
469   Chaio por Phawo Shrine is the most popular pra...   
4129  Took a fast boat for a magical day at Hapla Be...   
2132  in the twelfe-year animal cycle the rabbit is ...   
247   We went on a weekday and was pleased that this...   
4011  A small group of shops and restaurants created...   

                            review_subject        trip_type  rating  \
4205                     Not to be Missed!          Couples       5   
1665                             Nice view  Friends getaway       5   
3121                Beautiful and peaceful             NONE       5   
3126          temple that next to the road          Couples       3   
3688            i love this island so much      Solo travel       5   
...                                    ...              ...     ...   
469   Most Respect shine in Mae sot People             NONE       5   
4129                              Blissful          Couples       5   
2132                     the rabbit temple          Couples       5   
247                         Best Jodd Fair  Friends getaway       5   
4011              A manufactured village …           Family       3   

                                 location_name                  province  \
4205   The Royal Agricultural Station Angkhang                Phetchabun   
1665                     Chado Cliff Viewpoint  Phra Nakhon Si Ayutthaya   
3121                            Doi Mae Salong              Nakhon Sawan   
3126  Chedi Phra Borommasaririkkathat Khao Kho              Nakhon Sawan   
3688                          Thong Lang Beach                 Sukhothai   
...                                        ...                       ...   
469                      Chao Por Phawo Shrine                Nonthaburi   
4129                       Koh Kho Khao Island                Phetchabun   
2132                   Wat Phrathat Chae Haeng                 Sing Buri   
247                      Jodd Fairs DanNeramit                   Bangkok   
4011            Turtle Village Shops & Cuisine                   Phichit   

       place_id emotion                                     cleaned_review  \
4205  P03012884     joy  place real gem nestling cool green upland doi ...   
1665  P03017905     joy  nice view need careful hiking natural trail be...   
3121  P03016134     joy  doi mae salong beautiful interesting place vis...   
3126  P03016132     joy  located way back accommodation look time avail...   
3688  P03025214     joy  stayed koh larn castello resort christmas enjo...   
...         ...     ...                                                ...   
469   P03016494     joy  chaio por phawo shrine popular pray respect pl...   
4129  P03004050     joy  took fast boat magical day hapla beach real ro...   
2132  P03013402     joy  twelfeyear animal cycle rabbit one wat phra ch...   
247   P03022261     joy  went weekday pleased jodd fair wasnt packed ma...   
4011  P03018368     joy  small group shop restaurant created support co...   

                             

In [150]:

predictions_df = pd.DataFrame({
    'location_id': filtered_reviews['location_id'],
    'location_name': filtered_reviews['location_name'],
    'trip_type': filtered_reviews['trip_type'],
    'rating': filtered_reviews['rating'],
    'helpful_voting': filtered_reviews['helpful_votes'],
    'review_text': filtered_reviews['review'],  # Assuming X_test is a subset with a specific index
    'actual_sentiment': predict_df['sentiment'],  # The actual sentiment labels
    'predicted_sentiment': predict_df['predicted']  # The predicted sentiment labels
})

# predictions_df['actual_sentiment'] = predictions_df['actual_sentiment'].map(label_mapping)
# predictions_df['predicted_sentiment'] = predictions_df['predicted_sentiment'].map(label_mapping)

predictions_df.head(5)


location_id                                    location_name    trip_type  \
8     2273363.0  Wat Rajapradit Sathitmahasimaram Rajaworavihara         NONE   
14     311043.0                               Wat Phra Chetuphon      Couples   
17     317504.0                        Temple Of Dawn (Wat Arun)  Solo travel   
19     317504.0                        Temple Of Dawn (Wat Arun)       Family   
23     456322.0                                        Wat Umong       Family   

    rating  helpful_voting                                        review_text  \
8      5.0             2.0  One of the least crowded temples but very beau...   
14     5.0             0.0  The designs, the Buddhas, and other figures fe...   
17     5.0            15.0  Known as Temple of Dawn, I went to this temple...   
19     4.0             0.0  I have to admit that this is a place i have al...   
23     5.0             0.0  The visit to this temple was a good pick for u...   

   actual_sentiment  predicted_sentiment  
8                 2                    1  
14                1                    1  
17                0                    0  
19                0                    0  
23                1                    2

In [151]:
predictions_df.to_csv('./output/LSTM_predictions.csv')

In [138]:
y_val = y_val.astype(int)
ensemble_preds_class = ensemble_preds.astype(int)


In [139]:
print(y_val.shape)            # Shape of y_val
print(ensemble_preds.shape) 

(1723,)
(1723,)


In [140]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Calculate precision, recall, and F1-score directly using ensemble_preds
precision = precision_score(y_val, ensemble_preds, average='weighted')
recall = recall_score(y_val, ensemble_preds, average='weighted')
f1 = f1_score(y_val, ensemble_preds, average='weighted')

# Print the results
print(f'Precision: {precision:.4f}')
print(f'Recall: {recall:.4f}')
print(f'F1-Score: {f1:.4f}')


Precision: 0.6930
Recall: 0.6883
F1-Score: 0.6807


In [167]:
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import label_binarize

# Assume y_test contains true class labels, and y_pred_prob contains predicted probabilities

# Binarize the output labels for calculating AUC
y_test_bin = label_binarize(y_test, classes=[0, 1, 2])  # Assuming 3 classes: 0, 1, 2

# Calculate the AUC for each class
auc_macro = roc_auc_score(y_test_bin, y_pred_prob, average='macro', multi_class='ovr')
auc_micro = roc_auc_score(y_test_bin, y_pred_prob, average='micro', multi_class='ovr')

print(f'Macro-Averaged AUC: {auc_macro:.4f}')
print(f'Micro-Averaged AUC: {auc_micro:.4f}')

Macro-Averaged AUC: 0.5000
Micro-Averaged AUC: 0.8566


In [165]:
from sklearn.metrics import log_loss

# Calculate log loss
log_loss_value = log_loss(y_test, y_pred_prob)
print(f'Log Loss: {log_loss_value:.4f}')

Log Loss: 0.7264


In [166]:
from sklearn.metrics import cohen_kappa_score

# Calculate Cohen's Kappa
kappa = cohen_kappa_score(y_test, y_pred_class)
print(f"Cohen's Kappa: {kappa:.4f}")

Cohen's Kappa: 0.0000
